/**
 * Suggestion lists for the profile form. These are autofill shortcuts only —
 * students can always type a program name that isn't listed here.
 */

export const DEGREES = [
  "Bachelor of Arts (BA)",
  "Bachelor of Science (BS)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Engineering (BE)",
  "Bachelor of Science in Engineering (BSE)",
  "Bachelor of Science in Nursing (BSN)",
  "Bachelor of Architecture (BArch)",
  "Bachelor of Music (BM)",
  "Bachelor of Social Work (BSW)",
  "Bachelor of Applied Science (BAS)",
  "Bachelor of Computer Science (BCS)",
  "Bachelor of Education (BEd)",
  "Bachelor of Public Health (BSPH)",
  "Associate of Arts (AA)",
  "Associate of Science (AS)",
  "Associate of Applied Science (AAS)",
  "Master of Arts (MA)",
  "Master of Science (MS)",
  "Master of Business Administration (MBA)",
  "Master of Public Health (MPH)",
  "Master of Education (MEd)",
  "Master of Engineering (MEng)",
  "Master of Social Work (MSW)",
  "Master of Fine Arts (MFA)",
  "Master of Public Policy (MPP)",
  "Doctor of Philosophy (PhD)",
  "Doctor of Medicine (MD)",
  "Doctor of Pharmacy (PharmD)",
  "Doctor of Nursing Practice (DNP)",
  "Juris Doctor (JD)",
] as const;

export const YEARS = [
  "Freshman",
  "Sophomore",
  "Junior",
  "Senior",
  "Fifth year",
  "Transfer student",
  "Part-time student",
  "Post-baccalaureate",
  "Graduate student",
] as const;

/** Common U.S. undergraduate fields of study, usable as either a major or a minor. */
export const FIELDS_OF_STUDY = [
  "Accounting",
  "Actuarial Science",
  "Advertising",
  "Aerospace Engineering",
  "African American Studies",
  "Agricultural Science",
  "American Studies",
  "Animal Science",
  "Anthropology",
  "Applied Mathematics",
  "Arabic",
  "Archaeology",
  "Architecture",
  "Art History",
  "Artificial Intelligence",
  "Asian Studies",
  "Astronomy",
  "Astrophysics",
  "Athletic Training",
  "Biochemistry",
  "Bioengineering",
  "Bioinformatics",
  "Biology",
  "Biomedical Engineering",
  "Biostatistics",
  "Business Administration",
  "Business Analytics",
  "Chemical Engineering",
  "Chemistry",
  "Chinese",
  "Cinema and Media Studies",
  "Civil Engineering",
  "Classics",
  "Climate Science",
  "Cognitive Science",
  "Communication Studies",
  "Comparative Literature",
  "Computer Engineering",
  "Computer Science",
  "Construction Management",
  "Creative Writing",
  "Criminal Justice",
  "Criminology",
  "Cybersecurity",
  "Dance",
  "Data Science",
  "Dental Hygiene",
  "Dietetics",
  "Digital Media",
  "Early Childhood Education",
  "Earth Science",
  "Ecology",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Elementary Education",
  "Engineering Physics",
  "English",
  "Entrepreneurship",
  "Environmental Engineering",
  "Environmental Science",
  "Environmental Studies",
  "Epidemiology",
  "Ethnic Studies",
  "Exercise Science",
  "Family Studies",
  "Fashion Design",
  "Film Studies",
  "Finance",
  "Fine Arts",
  "Food Science",
  "Forensic Science",
  "Forestry",
  "French",
  "Gender Studies",
  "Genetics",
  "Geography",
  "Geology",
  "German",
  "Global Studies",
  "Graphic Design",
  "Greek",
  "Health Administration",
  "Health Informatics",
  "Health Policy and Management",
  "Health Sciences",
  "Hebrew",
  "Higher Education",
  "History",
  "Horticulture",
  "Hospitality Management",
  "Human Development",
  "Human Resources Management",
  "Industrial Design",
  "Industrial Engineering",
  "Information Science",
  "Information Systems",
  "Information Technology",
  "Interior Design",
  "International Business",
  "International Relations",
  "Italian",
  "Japanese",
  "Journalism",
  "Kinesiology",
  "Korean",
  "Landscape Architecture",
  "Latin",
  "Latin American Studies",
  "Law and Society",
  "Liberal Arts",
  "Linguistics",
  "Management",
  "Management Information Systems",
  "Marine Biology",
  "Marketing",
  "Materials Science and Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Media Studies",
  "Medical Laboratory Science",
  "Medieval Studies",
  "Meteorology",
  "Microbiology",
  "Middle Eastern Studies",
  "Military Science",
  "Molecular Biology",
  "Music",
  "Music Education",
  "Music Performance",
  "Nanoscience",
  "Neuroscience",
  "Nuclear Engineering",
  "Nursing",
  "Nutrition",
  "Occupational Therapy",
  "Ocean Engineering",
  "Operations Management",
  "Optometry",
  "Organizational Leadership",
  "Peace and Conflict Studies",
  "Petroleum Engineering",
  "Pharmaceutical Sciences",
  "Pharmacology",
  "Philosophy",
  "Photography",
  "Physical Therapy",
  "Physics",
  "Physiology",
  "Plant Biology",
  "Political Science",
  "Portuguese",
  "Pre-Dental",
  "Pre-Law",
  "Pre-Medicine",
  "Pre-Pharmacy",
  "Pre-Veterinary Medicine",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Public Policy",
  "Public Relations",
  "Quantitative Biology",
  "Radiologic Sciences",
  "Real Estate",
  "Recreation Management",
  "Religious Studies",
  "Respiratory Therapy",
  "Risk Management and Insurance",
  "Robotics",
  "Russian",
  "Sociology",
  "Software Engineering",
  "Soil Science",
  "Spanish",
  "Special Education",
  "Speech-Language Pathology",
  "Sports Administration",
  "Statistics",
  "Statistics and Analytics",
  "Studio Art",
  "Supply Chain Management",
  "Sustainability Studies",
  "Systems Engineering",
  "Theatre",
  "Toxicology",
  "Urban Planning",
  "Urban Studies",
  "Veterinary Science",
  "Wildlife Biology",
  "Women's and Gender Studies",
  "Writing and Rhetoric",
  "Zoology",
] as const;

/** Minors students commonly add on top of a major, beyond the shared field list. */
export const MINOR_ONLY = [
  "Business Essentials",
  "Data Literacy",
  "Entrepreneurship and Innovation",
  "Ethics",
  "Global Health",
  "Leadership",
  "Medical Anthropology",
  "Science Communication",
  "Social and Economic Justice",
  "Technology and Society",
] as const;

export const MINORS = [...FIELDS_OF_STUDY, ...MINOR_ONLY].sort((a, b) => a.localeCompare(b));
