/**
 * Autofill suggestion lists for the Interests & strengths section.
 * These are shortcuts only — students can always add their own text.
 */

export const INTEREST_OPTIONS = [
  "Healthcare",
  "Technology",
  "Problem solving",
  "Research",
  "Data and statistics",
  "Design",
  "Writing",
  "Public speaking",
  "Teaching and mentoring",
  "Business and strategy",
  "Entrepreneurship",
  "Finance",
  "Marketing",
  "Law and policy",
  "Sustainability",
  "Environment",
  "Engineering",
  "Robotics",
  "Artificial intelligence",
  "Cybersecurity",
  "Video games",
  "Music",
  "Art and illustration",
  "Film and media",
  "Sports and fitness",
  "Psychology",
  "Neuroscience",
  "Genetics",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Astronomy",
  "Education",
  "Social justice",
  "Community service",
  "International affairs",
  "Languages",
  "History",
  "Philosophy",
  "Architecture",
  "Agriculture",
  "Food science",
  "Travel",
  "Journalism",
  "Product management",
  "Human behavior",
  "Animals and veterinary care",
  "Emergency medicine",
  "Public health",
] as const;

export const CAREER_INTEREST_OPTIONS = [
  "Healthcare technology",
  "Data science",
  "Biotechnology",
  "Software engineering",
  "Medicine",
  "Nursing",
  "Physician assistant",
  "Pharmacy",
  "Dentistry",
  "Physical therapy",
  "Public health",
  "Epidemiology",
  "Genetic counseling",
  "Clinical research",
  "Machine learning engineering",
  "Cybersecurity analysis",
  "Product management",
  "UX design",
  "Data analytics",
  "Business analytics",
  "Consulting",
  "Investment banking",
  "Accounting",
  "Financial analysis",
  "Marketing",
  "Sales",
  "Human resources",
  "Law",
  "Policy analysis",
  "Nonprofit management",
  "Teaching",
  "School counseling",
  "Academic research",
  "Civil engineering",
  "Mechanical engineering",
  "Electrical engineering",
  "Biomedical engineering",
  "Environmental science",
  "Renewable energy",
  "Architecture",
  "Journalism",
  "Communications",
  "Graphic design",
  "Game development",
  "Film production",
  "Sports management",
  "Social work",
  "Veterinary medicine",
  "Aerospace",
  "Supply chain management",
] as const;

export const SKILL_OPTIONS = [
  "Lab technique",
  "Scientific writing",
  "Spreadsheet analysis",
  "Programming",
  "Python",
  "Java",
  "JavaScript",
  "SQL and databases",
  "Statistics",
  "Data visualization",
  "Machine learning",
  "Research design",
  "Technical writing",
  "Public speaking",
  "Presentation design",
  "Project management",
  "Teamwork",
  "Leadership",
  "Time management",
  "Critical thinking",
  "Problem solving",
  "Attention to detail",
  "Customer service",
  "Sales and persuasion",
  "Financial modeling",
  "Accounting basics",
  "Marketing strategy",
  "Social media",
  "Graphic design",
  "UX research",
  "Prototyping",
  "CAD and drafting",
  "Circuit design",
  "Field work",
  "Patient care",
  "Clinical observation",
  "Medical terminology",
  "Tutoring",
  "Mentoring",
  "Event planning",
  "Fundraising",
  "Editing and proofreading",
  "Foreign language",
  "Spanish",
  "Interviewing",
  "Note taking",
  "Grant writing",
  "Data entry accuracy",
  "Quality control",
  "Ethical reasoning",
] as const;
